### ISSUE TITLE
jjgoal does not work for users without watersize.

### ISSUE THREAD

**Issue by zskelto** [r3cebarnett/waterbuddy#24]
New user (Cameron) was unable to set their jumping jack goal until they used the watersize command. Bot did not send a reply at all to ".jjgoal 40" until watersize was used.

**Comment by r3cebarnett** [comment]
Ignoring exception in command jumpingjackgoal:
Traceback (most recent call last):
  File "C:\Users\maura\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\maura\Documents\Github\waterbuddy\waterbuddy\cogs\Workout.py", line 318, in jumpingjackgoal
    user = model.settings_factor(ctx.author_id, jumpingjack_goal=val)
AttributeError: module 'db.model' has no attribute 'settings_factor'
